import HomePage from '@/screens/Home';
import Head from 'next/head'
import dynamic from 'next/dynamic';

// const DynamicPage = dynamic(()=> import('@/screens/Home'), {
//   loading: ()=> <p>Loading... dynamico</p>
// }) 
// aparentemente não teve nenhuma diferença significativa, talvez funcione apenas com componentes menores

export default function Home() {
 
  return (
    <>
     <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage/>

    </>
  )
}
