import Head from 'next/head'
import { useSelector, useDispatch } from 'react-redux';
import { useEffect } from 'react'
import { addToPokedex } from '@/store/reducers/pokemon';
import { getDetails } from '@/store/reducers/selectedPokemon';
import { Header } from '@/components/header/Header';
import PokemonCard from '@/components/pokemonCard/PokemonCard';

export default function Home() {
  const dispatch = useDispatch();
  const pokemon = useSelector((state) => state.pokemon)
 
  useEffect(() => {
    dispatch(getDetails("pikachu"))
  }, [])

  // const addPokedex = (pokemon) => {
  //   dispatch(addToPokedex(pokemon))
  // }

  return (
    <div>
      <Head>
        <title>Pokedex</title> 
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div>
        <h2 > Todos Pokémons</h2>

        {pokemon === "carregando" ? <p>loading</p> : pokemon.map(i => <PokemonCard key={i.id} pokemon={i} />)}
      </div>

    </div>
  )
}
